<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FAST" Id="{9f60d674-6dff-480f-9336-a78c45dbc093}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FAST
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="FAST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>