<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="SLOW" Id="{3bd6c98f-32d6-4aaa-ac41-823b5a11695e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SLOW
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="SLOW">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>