<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="Prg_Counter" Id="{56949bcf-47d4-4045-9858-74c2a0ec070a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Prg_Counter
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Prg_Counter">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>